# Generated by Django 5.2.14 on 2026-05-27 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("places", "0002_place_phone_place_website"),
        ("taxonomy", "0002_seed_taxonomy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("url", models.URLField(blank=True, max_length=500)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ical", "iCalendar feed"),
                            ("google", "Google"),
                            ("user", "User-submitted"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="taxonomy.activitytype",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
                "indexes": [
                    models.Index(
                        fields=["place", "starts_at"],
                        name="events_even_place_i_92c0e1_idx",
                    ),
                    models.Index(
                        fields=["starts_at"], name="events_even_starts__b01102_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_id", ""), _negated=True),
                        fields=("source", "external_id"),
                        name="uq_event_source_external",
                    )
                ],
            },
        ),
    ]
