# Generated by Django 5.2.14 on 2026-06-12 21:27

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('places', '0005_placeactivity_is_disputed_activityedgevote_and_more'),
        ('taxonomy', '0005_seed_reading_archives'),
    ]

    operations = [
        # Idempotent (CREATE EXTENSION IF NOT EXISTS) — duplicated in social/0016 because
        # the two apps' migration graphs are independent and either may run first. The
        # reverse is a deliberate NO-OP (social/0016's TrigramExtension is the single
        # owner of the drop) so rolling back ONE app can't break the other's indexes.
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='event_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='event_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
