# Generated by Django 5.2.14 on 2026-06-12 23:01

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventfeed'),
        ('places', '0005_placeactivity_is_disputed_activityedgevote_and_more'),
        ('taxonomy', '0005_seed_reading_archives'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='event_title_trgm',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='event_desc_trgm',
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='event_title_trgm'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'), name='event_desc_trgm'),
        ),
    ]
