# Generated by Django 5.2.14 on 2026-06-13 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_event_title_trgm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cancelled', 'Cancelled'), ('moved', 'Moved / wrong place'), ('wrong_time', 'Wrong time')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.event')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'created_at'], name='events_even_event_i_d9c109_idx'), models.Index(fields=['event', 'reporter'], name='events_even_event_i_b49e52_idx')],
            },
        ),
    ]
