# Generated by Django 5.2.14 on 2026-05-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="recurring",
            field=models.BooleanField(default=False),
        ),
    ]
