# Generated by Django 5.2.14 on 2026-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('period', models.CharField(blank=True, max_length=60)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0)), name='spendentry_nonneg_amount')],
            },
        ),
    ]
