# Generated by Django 5.2.14 on 2026-05-30 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_spendentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('goal_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['is_active'], name='donations_c_is_acti_631402_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('goal_cents__gte', 100)), name='campaign_goal_min')],
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.campaign'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign', 'status'], name='donations_d_campaig_5c4298_idx'),
        ),
    ]
