# Generated by Django 5.2.15 on 2026-06-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_campaign_donation_campaign_and_more'),
        ('places', '0009_placecorrection_placecorrectionconfirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Optional verified civic partner this campaign credits on /campaigns/.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='places.partner'),
        ),
    ]
