# Generated by Django 5.2.14 on 2026-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0006_campaign_closed_at_campaign_outcome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=280)),
                ("amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("spend_category", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-amount_cents", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_cents__gte", 1)),
                        name="costanchor_positive_amount",
                    )
                ],
            },
        ),
    ]
