# Generated by Django 5.2.14 on 2026-06-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0007_costanchor"),
        ("places", "0004_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="InKindContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category", models.CharField(max_length=120)),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("unit_text", models.CharField(blank=True, max_length=60)),
                ("value_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("period", models.CharField(blank=True, max_length=60)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional verified civic partner credited for this contribution.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="in_kind_contributions",
                        to="places.partner",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
