# Generated by Django 5.2.14 on 2026-06-17 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_inkindcontribution'),
        ('places', '0013_alter_placecorrection_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=280)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('period', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(blank=True, help_text='Optional verified civic partner credited for this outcome.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civic_outcomes', to='places.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
