# Generated by Django 5.2.14 on 2026-06-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_consumedagenonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='ageassurance',
            name='reverify_notice',
            field=models.CharField(blank=True, choices=[('', 'None'), ('soon', 'Expiring-soon nudge sent'), ('expired', 'Expired / paused notice sent')], default='', max_length=8),
        ),
    ]
