# Generated by Django 5.2.14 on 2026-06-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ageassurance_reverify_notice'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cohort', 'is_identity_verified'], name='accounts_us_cohort_ff510e_idx'),
        ),
    ]
