# Generated by Django 5.2.14 on 2026-06-13 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_accounts_us_cohort_ff510e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianGuardrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervised_only', models.BooleanField(default=False)),
                ('latest_start_hour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('max_open_joins', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardrail', to='accounts.guardianrelationship')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('latest_start_hour__isnull', True), models.Q(('latest_start_hour__gte', 0), ('latest_start_hour__lte', 23)), _connector='OR'), name='guardrail_latest_start_hour_range'), models.CheckConstraint(condition=models.Q(('max_open_joins__isnull', True), models.Q(('max_open_joins__gte', 1), ('max_open_joins__lte', 50)), _connector='OR'), name='guardrail_max_open_joins_range')],
            },
        ),
    ]
