# Generated by Django 5.2.14 on 2026-06-16 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_guardianguardrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianguardrail',
            name='allowed_weekdays',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='guardianguardrail',
            name='earliest_start_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
