# Generated by Django 5.2.14 on 2026-06-16 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_guardianguardrail_allowed_weekdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianguardrail',
            name='allowed_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=80), blank=True, default=list, size=None),
        ),
    ]
