# Generated by Django 5.2.14 on 2026-06-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_guardianguardrail_allowed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentalconsent',
            name='renewal_notice',
            field=models.CharField(blank=True, choices=[('', 'None'), ('soon', 'Renewal nudge sent')], default='', max_length=8),
        ),
    ]
