# Generated by Django 5.2.15 on 2026-07-12 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bannedidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveSmallIntegerField()),
                ('salt', models.PositiveSmallIntegerField(default=0)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
