# Generated by Django 5.2.14 on 2026-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_keyverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="disappearing_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
