# Generated by Django 5.2.14 on 2026-05-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_conversation_disappearing_seconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("member", "Member"),
                    ("guardian", "Guardian (observer)"),
                ],
                default="member",
                max_length=8,
            ),
        ),
    ]
