"""The vendored `/v1` client core must stay a faithful copy (romania_scraper ADR-0069).

`_roedu_client_core.py` is generated by the producer's
`scripts/sync_roedu_client.py`. These tests catch a local hand-edit through the
embedded stamp, pin the seam (shared transport/pagination, local redistributability
gate), and pin the **defect adoption fixed**.

The defect: this app's private `iter()` followed `next_cursor` until it was falsy
with no repeated-cursor guard, and `max_records` defaults to `None` — so there was
no bound of any kind. A server or bug echoing one cursor made it re-yield the same
page forever. `iter_app_pack()` always had the guard; the product walk did not.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from django.test import SimpleTestCase

from apps.ingestion.sources import roedu_client as rc
from apps.ingestion.sources._roedu_client_core import VENDORED_SHA256, RoeduContractError
from apps.ingestion.sources._roedu_client_core import RoeduClient as CanonicalClient

CORE = Path(__file__).resolve().parents[1] / "sources/_roedu_client_core.py"

_BEGIN = "# --- BEGIN VENDORED romania_scraper/dataapi/roedu_client.py ---"
_END = "# --- END VENDORED ---"


def _page(records, *, next_cursor=None, available=True):
    body = {"available": available, "records": records}
    if next_cursor is not None:
        body["next_cursor"] = next_cursor
    return body


class _FakeClient(rc.RoeduClient):
    """Stubs only the HTTP page fetch, so the real paging logic is exercised."""

    def __init__(self, pages):
        super().__init__(base_url="http://test", api_key="k")
        self._pages = list(pages)
        self.calls = 0

    def page(self, product, *, cursor=None, limit=200, **filters):  # noqa: ARG002
        self.calls += 1
        # Deliberately unbounded: a stuck-cursor server would keep answering, which
        # is exactly what the old loop could not survive.
        return self._pages[min(self.calls - 1, len(self._pages) - 1)]


class VendoredCopyIntegrityTests(SimpleTestCase):
    def test_vendored_copy_has_not_been_hand_edited(self):
        text = CORE.read_text(encoding="utf-8")
        body = text.split(_BEGIN, 1)[1].split(_END, 1)[0].strip("\n") + "\n"
        self.assertEqual(
            hashlib.sha256(body.encode("utf-8")).hexdigest(),
            VENDORED_SHA256,
            "_roedu_client_core.py was edited locally; edit the canonical file in "
            "romania_scraper and re-run scripts/sync_roedu_client.py --write",
        )

    def test_historical_import_path_still_works(self):
        self.assertTrue(issubclass(rc.RoeduClient, CanonicalClient))
        self.assertIs(rc.RoeduContractError, RoeduContractError)

    def test_contract_error_is_one_class_across_the_seam(self):
        """The domain layer raises it and shared paging raises it; an `except` in
        this app must catch both, so they must not be two same-named classes."""
        self.assertIs(rc.RoeduContractError, RoeduContractError)
        self.assertTrue(issubclass(RoeduContractError, ValueError))


class SeamTests(SimpleTestCase):
    def test_transport_and_paging_come_from_the_shared_core(self):
        for name in ("_get", "health", "products", "page", "pages", "iter"):
            with self.subTest(method=name):
                self.assertIs(
                    getattr(rc.RoeduClient, name),
                    getattr(CanonicalClient, name),
                    f"{name} should be inherited, not redefined locally",
                )

    def test_this_app_gains_the_page_walk_it_never_had(self):
        """Adoption also added `pages()`, which this app's private copy lacked
        entirely — page-level snapshot/release metadata is now reachable."""
        self.assertTrue(hasattr(rc.RoeduClient, "pages"))

    def test_redistributability_gate_stays_local(self):
        """Deciding what may be published is this app's gate, not /v1 transport."""
        for name in ("app_pack_page", "iter_app_pack", "read_app_pack"):
            with self.subTest(method=name):
                self.assertIn(name, vars(rc.RoeduClient))
                self.assertFalse(hasattr(CanonicalClient, name))
        for fn in ("is_redistributable_app_pack_item", "is_canonical_social_app_pack_item"):
            with self.subTest(function=fn):
                self.assertTrue(callable(getattr(rc, fn)))


class RepeatedCursorDefectTests(SimpleTestCase):
    """The defect adoption fixed, pinned so it cannot come back."""

    def test_product_iteration_no_longer_loops_forever_on_a_stuck_cursor(self):
        client = _FakeClient([_page([{"id": "v1"}], next_cursor="stuck")])
        with self.assertRaises(RoeduContractError):
            list(client.iter("venues"))
        # The point is that it STOPS. Without the guard this consumed pages
        # indefinitely, since max_records defaults to None.
        self.assertLessEqual(client.calls, 3)

    def test_two_distinct_cursors_then_repeat_still_fails_closed(self):
        client = _FakeClient(
            [
                _page([{"id": "v1"}], next_cursor="a"),
                _page([{"id": "v2"}], next_cursor="b"),
                _page([{"id": "v3"}], next_cursor="a"),
            ]
        )
        with self.assertRaises(RoeduContractError):
            list(client.iter("venues"))

    def test_normal_paging_and_max_records_still_work(self):
        client = _FakeClient([_page([{"id": "v1"}], next_cursor="a"), _page([{"id": "v2"}])])
        self.assertEqual([r["id"] for r in client.iter("venues")], ["v1", "v2"])

        capped = _FakeClient([_page([{"id": "a"}, {"id": "b"}, {"id": "c"}], next_cursor="a")])
        self.assertEqual(len(list(capped.iter("venues", max_records=2))), 2)

    def test_unavailable_page_is_fail_closed(self):
        client = _FakeClient([_page([{"id": "v1"}], available=False)])
        self.assertEqual(list(client.iter("venues")), [])
