# Generated by Django 5.2.14 on 2026-05-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0005_seed_reading_archives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('derive_method', models.CharField(choices=[('city', 'Whole city'), ('grid', 'Snapped grid cell'), ('cluster', 'Venue cluster'), ('polygon', 'Admin polygon')], default='city', max_length=12)),
                ('min_radius_m', models.PositiveIntegerField(default=1500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('city', 'slug'), name='uq_area_city_slug')],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(choices=[('unassigned', 'Unassigned'), ('child', 'Child (under 16)'), ('teen', 'Teen (16-17)'), ('adult', 'Adult (18+)')], max_length=16)),
                ('tier', models.CharField(choices=[('type', 'Activity type'), ('category', 'Category')], max_length=8)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('is_published', models.BooleanField(default=False)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='taxonomy.activitytype')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='communities.area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communities', to='taxonomy.activitycategory')),
            ],
            options={
                'indexes': [models.Index(fields=['cohort', 'is_published', 'area'], name='communities_cohort_d23bed_idx'), models.Index(fields=['cohort', 'is_published', 'category'], name='communities_cohort_052979_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activity_type__isnull', False)), fields=('cohort', 'area', 'activity_type'), name='uq_community_type'), models.UniqueConstraint(condition=models.Q(('activity_type__isnull', True)), fields=('cohort', 'area', 'category'), name='uq_community_category'), models.CheckConstraint(condition=models.Q(models.Q(('activity_type__isnull', False), ('tier', 'type')), models.Q(('activity_type__isnull', True), ('tier', 'category')), _connector='OR'), name='community_tier_matches_type')],
            },
        ),
    ]
