# Generated by Django 5.2.14 on 2026-05-27 18:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=64)),
                ("target_ref", models.CharField(blank=True, max_length=128)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("prev_hash", models.CharField(blank=True, max_length=64)),
                ("hash", models.CharField(db_index=True, max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("grooming", "Grooming / predatory contact"),
                            ("harassment", "Harassment / bullying"),
                            ("csam", "Child sexual abuse material"),
                            ("spam", "Spam"),
                            ("off_platform", "Unsafe off-platform / meetup risk"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewing", "Reviewing"),
                            ("actioned", "Actioned"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.PositiveBigIntegerField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("warn", "Warn"),
                            ("remove", "Remove content"),
                            ("suspend", "Suspend account"),
                            ("ban", "Ban account"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("grooming", "Grooming / predatory contact"),
                            ("harassment", "Harassment / bullying"),
                            ("csam", "Child sexual abuse material"),
                            ("spam", "Spam"),
                            ("off_platform", "Unsafe off-platform / meetup risk"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="safety.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("blocker", "blocked"), name="uq_block_pair"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("blocker", models.F("blocked")), _negated=True
                        ),
                        name="block_not_self",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "reason"], name="safety_repo_status_36179d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="safety_repo_target__d6ed0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moderationaction",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="safety_mode_target__e72dc5_idx",
            ),
        ),
    ]
