# Generated by Django 5.2.14 on 2026-05-29 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_moderationaction_lifted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocked'], name='safety_bloc_blocked_26e97c_idx'),
        ),
    ]
