# Generated by Django 5.2.14 on 2026-05-29 18:47

from django.db import migrations, models


def _backfill_actor_ref(apps, schema_editor):
    """Copy existing actor_id -> actor_ref. The hash chain was computed over actor_id, so
    seeding actor_ref with the same value keeps verify_audit_chain() valid for pre-existing
    rows; future GDPR erasures NULL the actor FK but leave actor_ref intact."""
    AuditLog = apps.get_model("safety", "AuditLog")
    AuditLog.objects.filter(actor_ref__isnull=True, actor__isnull=False).update(
        actor_ref=models.F("actor_id")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0003_block_safety_bloc_blocked_26e97c_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_ref",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_actor_ref, migrations.RunPython.noop),
    ]
