# Generated by Django 5.2.14 on 2026-06-03 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_auditlog_actor_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_ref', '-id'], name='safety_audit_actor_id_idx'),
        ),
    ]
