# Generated by Django 5.2.14 on 2026-06-20 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0005_auditlog_safety_audit_actor_id_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(
                choices=[
                    ('warn', 'Warn'),
                    ('remove', 'Remove content'),
                    ('suspend', 'Suspend account'),
                    ('timed_ban', 'Timed ban'),
                    ('ban', 'Ban account'),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name='AuthorityReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ref', models.UUIDField()),
                ('reason', models.CharField(choices=[('grooming', 'Grooming / predatory contact'), ('harassment', 'Harassment / bullying'), ('csam', 'Child sexual abuse material'), ('spam', 'Spam'), ('off_platform', 'Unsafe off-platform / meetup risk'), ('other', 'Other')], max_length=24)),
                ('authority', models.CharField(choices=[('inhope', 'INHOPE / national hotline'), ('igpr', 'Romanian Police (IGPR)'), ('police', 'Other law enforcement'), ('other', 'Other authority')], max_length=16)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('audit_anchor_hash', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='safety.report')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='authorityreferral',
            index=models.Index(fields=['subject_ref', '-id'], name='safety_referral_subj_idx'),
        ),
    ]
