# Generated by Django 5.2.15 on 2026-06-21 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0006_authorityreferral_timed_ban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('upheld', 'Upheld (decision stands)'), ('overturned', 'Overturned (decision reversed)')], default='pending', max_length=12)),
                ('decision_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='safety.moderationaction')),
                ('appellant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_filed', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='safety_appeal_status_idx')],
            },
        ),
    ]
