# Generated by Django 5.2.14 on 2026-05-29 18:39

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('social', '0003_activity_is_hidden_post_is_hidden'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activityembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='actemb_vector_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
