# Generated by Django 5.2.14 on 2026-06-07 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('social', '0015_activityseries_activity_series_and_more'),
        ('taxonomy', '0005_seed_reading_archives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(choices=[('unassigned', 'Unassigned'), ('child', 'Child (under 16)'), ('teen', 'Teen (16-17)'), ('adult', 'Adult (18+)')], max_length=16)),
                ('beginners', models.BooleanField(default=False)),
                ('cost_band', models.CharField(blank=True, choices=[('unspecified', 'Not specified'), ('free', 'Free'), ('low', 'Low cost'), ('paid', 'Paid')], default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saved_searches', to='taxonomy.activitytype')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saved_searches', to='communities.area')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saved_searches', to='taxonomy.activitycategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'saved searches',
                'indexes': [models.Index(fields=['cohort', 'activity_type'], name='saved_searc_cohort_be3642_idx'), models.Index(fields=['cohort', 'category'], name='saved_searc_cohort_6dcef4_idx'), models.Index(fields=['user'], name='saved_searc_user_id_fd92ab_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('activity_type__isnull', False), ('category__isnull', True)), models.Q(('activity_type__isnull', True), ('category__isnull', False)), _connector='OR'), name='savedsearch_type_xor_category')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearchMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'activity'), name='uq_savedsearchmatch_user_activity')],
            },
        ),
    ]
