# Generated by Django 5.2.14 on 2026-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("saved_searches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="coarse_window",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekday_daytime", "Weekday daytime"),
                    ("weekday_evening", "Weekday evening"),
                    ("weekend_daytime", "Weekend daytime"),
                    ("weekend_evening", "Weekend evening"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
