# Generated by Django 5.1.15 on 2026-05-27 15:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        # Enable PostGIS before creating any geometry column. Idempotent
        # (CREATE EXTENSION IF NOT EXISTS), so it's a no-op on the Docker
        # postgis image and on databases where it is already enabled.
        CreateExtension("postgis"),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("address_street", models.CharField(blank=True, max_length=255)),
                ("address_housenumber", models.CharField(blank=True, max_length=32)),
                ("address_city", models.CharField(blank=True, max_length=128)),
                ("address_postcode", models.CharField(blank=True, max_length=32)),
                ("address_country", models.CharField(blank=True, max_length=2)),
                ("opening_hours_raw", models.CharField(blank=True, max_length=255)),
                ("opening_hours", models.JSONField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("osm", "OpenStreetMap"),
                            ("overture", "Overture Maps"),
                            ("google", "Google"),
                            ("user", "User-submitted"),
                        ],
                        max_length=16,
                    ),
                ),
                ("osm_type", models.CharField(blank=True, max_length=8)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("raw_tags", models.JSONField(blank=True, default=dict)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlaceActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("inferred", "Inferred from tags"),
                            ("confirmed", "User-confirmed"),
                            ("manual", "Manually added"),
                        ],
                        default="inferred",
                        max_length=16,
                    ),
                ),
                ("confidence", models.FloatField(default=0.5)),
                ("source", models.CharField(default="osm", max_length=16)),
                ("mapping_rule", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="place_activities",
                        to="taxonomy.activitytype",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_activities",
                        to="places.place",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="activities",
            field=models.ManyToManyField(
                related_name="places",
                through="places.PlaceActivity",
                to="taxonomy.activitytype",
            ),
        ),
        migrations.AddIndex(
            model_name="placeactivity",
            index=models.Index(
                fields=["activity"], name="places_plac_activit_2aa231_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="placeactivity",
            constraint=models.UniqueConstraint(
                fields=("place", "activity"), name="uq_place_activity"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["address_city"], name="places_plac_address_d00f12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["source"], name="places_plac_source_9b0f1d_idx"),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "osm")),
                fields=("osm_type", "osm_id"),
                name="uq_place_osm",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("source", "external_id"),
                name="uq_place_external",
            ),
        ),
    ]
