# Generated by Django 5.2.14 on 2026-05-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="phone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="place",
            name="website",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
