# Generated by Django 5.2.14 on 2026-05-30 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_accesspreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('library', 'Library'), ('school', 'School'), ('ngo', 'NGO / nonprofit'), ('civic', 'Civic body'), ('healthcare', 'Healthcare'), ('cultural', 'Cultural'), ('other', 'Other')], max_length=16)),
                ('blurb', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(280)])),
                ('website', models.URLField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='places.place')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_verified', 'is_active'], name='places_part_is_veri_ddff5e_idx')],
            },
        ),
    ]
