# Generated by Django 5.2.14 on 2026-05-30 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placeactivity',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ActivityEdgeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('confirm', 'Confirms'), ('dispute', 'Disputes')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_votes', to='places.placeactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_edge_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['edge', 'vote'], name='places_acti_edge_id_75645d_idx')],
                'constraints': [models.UniqueConstraint(fields=('edge', 'user'), name='uq_edge_vote_user')],
            },
        ),
        migrations.CreateModel(
            name='OpenNowReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_now_reports', to='places.place')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_now_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['place', 'created_at'], name='places_open_place_i_08698a_idx'), models.Index(fields=['place', 'reporter'], name='places_open_place_i_9102d1_idx')],
            },
        ),
    ]
