# Generated by Django 5.2.14 on 2026-06-13 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_placeactivity_is_disputed_activityedgevote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildVenueClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('osm_match', models.JSONField(blank=True, default=dict)),
                ('overture_categories', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'child venue class',
                'verbose_name_plural': 'child venue classes',
            },
        ),
        migrations.CreateModel(
            name='ApprovedChildVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_venue_approvals', to=settings.AUTH_USER_MODEL)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_approval', to='places.place')),
            ],
        ),
    ]
