# Generated by Django 5.2.14 on 2026-06-13 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_seed_child_venue_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceFactVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_key', models.CharField(choices=[('drinking_water', 'Drinking water'), ('toilets', 'Toilets'), ('lit_at_night', 'Lit at night'), ('indoor_shelter', 'Indoor shelter'), ('fenced', 'Fenced / away from traffic'), ('shade', 'Shade'), ('playground', 'Playground nearby')], max_length=24)),
                ('value', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_votes', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_fact_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['place', 'fact_key'], name='places_plac_place_i_cbcc88_idx')],
                'constraints': [models.UniqueConstraint(fields=('place', 'user', 'fact_key'), name='uq_place_fact_user')],
            },
        ),
    ]
