# Generated by Django 5.2.14 on 2026-06-13 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_placefactvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('name', 'Name'), ('address', 'Address')], max_length=16)),
                ('proposed_value', models.CharField(max_length=255)),
                ('required_confirmations', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='places.place')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_corrections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCorrectionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='places.placecorrection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_correction_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='placecorrection',
            index=models.Index(fields=['place', 'status'], name='places_plac_place_i_fa4cb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='placecorrection',
            constraint=models.CheckConstraint(condition=models.Q(('required_confirmations__gte', 1)), name='correction_quorum_positive'),
        ),
        migrations.AddConstraint(
            model_name='placecorrection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('place', 'field'), name='uq_one_pending_correction_per_field'),
        ),
        migrations.AddConstraint(
            model_name='placecorrectionconfirmation',
            constraint=models.UniqueConstraint(fields=('correction', 'user'), name='uq_correction_confirm_user'),
        ),
    ]
