# Generated by Django 5.2.15 on 2026-06-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_placecorrection_placecorrectionconfirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspreference',
            name='needs_hearing_loop',
            field=models.BooleanField(default=False),
        ),
    ]
