# Generated by Django 5.2.14 on 2026-06-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_accesspreference_needs_hearing_loop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placefactvote',
            name='fact_key',
            field=models.CharField(choices=[('drinking_water', 'Drinking water'), ('toilets', 'Toilets'), ('lit_at_night', 'Lit at night'), ('indoor_shelter', 'Indoor shelter'), ('fenced', 'Fenced / away from traffic'), ('shade', 'Shade'), ('playground', 'Playground nearby'), ('bike_parking', 'Bike parking'), ('car_parking', 'Car parking'), ('bus_tram_nearby', 'Bus/tram nearby')], max_length=24),
        ),
    ]
