# Generated by Django 5.2.14 on 2026-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0012_placeclosurereport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placecorrection",
            name="field",
            field=models.CharField(
                choices=[
                    ("name", "Name"),
                    ("address", "Address"),
                    ("hours", "Opening hours"),
                ],
                max_length=16,
            ),
        ),
    ]
