# Generated by Django 5.2.15 on 2026-07-07 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_placecover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='kind',
            field=models.CharField(choices=[('library', 'Library'), ('school', 'School'), ('ngo', 'NGO / nonprofit'), ('civic', 'Civic body'), ('healthcare', 'Healthcare'), ('cultural', 'Cultural'), ('business', 'Local business'), ('other', 'Other')], max_length=16),
        ),
        migrations.CreateModel(
            name='PlaceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('library', 'Library'), ('school', 'School'), ('ngo', 'NGO / nonprofit'), ('civic', 'Civic body'), ('healthcare', 'Healthcare'), ('cultural', 'Cultural'), ('business', 'Local business'), ('other', 'Other')], default='business', max_length=16)),
                ('official_website', models.URLField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('cui', models.CharField(blank=True, max_length=16)),
                ('evidence', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_claims', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_place_claims', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='places.partner')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='places.place')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='places_plac_status_e7123c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('place', 'claimant'), name='uq_placeclaim_pending_per_user')],
            },
        ),
    ]
