# Generated by Django 5.2.15 on 2026-07-07 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_alter_partner_kind_placeclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placecover',
            name='exif_stripped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placecover',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='placecover',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_place_covers', to=settings.AUTH_USER_MODEL),
        ),
    ]
