# Generated by Django 5.2.14 on 2026-05-27 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("profile", "Profile picture"),
                            ("thread", "Thread photo"),
                        ],
                        max_length=16,
                    ),
                ),
                ("storage_key", models.CharField(blank=True, max_length=128)),
                ("content_type", models.CharField(blank=True, max_length=64)),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("clean", "Clean"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("exif_stripped", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="social.thread",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["thread", "scan_status"],
                        name="media_photo_thread__7416ce_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "profile")),
                        fields=("uploader",),
                        name="uq_profile_photo_per_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("kind", "thread"), ("thread__isnull", False)),
                            models.Q(("kind", "profile"), ("thread__isnull", True)),
                            _connector="OR",
                        ),
                        name="photo_thread_matches_kind",
                    ),
                ],
            },
        ),
    ]
