# Generated by Django 5.2.14 on 2026-05-30 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_attachment'),
        ('social', '0011_postreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(condition=models.Q(('expires_at__isnull', False), ('purged_at__isnull', True)), fields=['expires_at'], name='ix_attachment_pending_purge'),
        ),
    ]
