# Generated by Django 5.2.14 on 2026-06-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_attachment_expires_at_attachment_purged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='phash',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
