# Generated by Codex on 2026-07-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0031_alter_activity_is_publicly_listed_and_more'),
        ('media', '0004_photo_phash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCover',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('storage_key', models.CharField(max_length=128)),
                ('content_type', models.CharField(max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('exif_stripped', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'activity',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cover',
                        to='social.activity',
                    ),
                ),
                (
                    'uploader',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='activity_covers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='activitycover',
            index=models.Index(
                fields=['activity', 'created_at'],
                name='media_activ_activity_6b122c_idx',
            ),
        ),
    ]
