# Generated by Django 5.2.9 on 2026-07-04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0005_activitycover"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activitycover",
            new_name="media_activ_activit_43933a_idx",
            old_name="media_activ_activity_6b122c_idx",
        ),
    ]
