# Generated by Django 5.2.15 on 2026-07-12 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_rename_media_activ_activity_6b122c_idx_media_activ_activit_43933a_idx'),
        ('social', '0035_remove_activity_fallback_meeting_point_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycover',
            name='thumb_storage_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='attachment',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='poster_content_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='attachment',
            name='poster_storage_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='attachment',
            name='processing_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attachment',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='source_storage_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('pending', 'Pending processing'), ('processing', 'Processing'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='ready', max_length=16),
        ),
        migrations.AddField(
            model_name='attachment',
            name='thumb_storage_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumb_storage_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('video', 'Video')], max_length=8),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='storage_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'processing'])), fields=['status', 'created_at'], name='ix_attachment_needs_work'),
        ),
    ]
