# Generated by Django 5.2.14 on 2026-05-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="guardian_accompanied",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("member", "Member"),
                    ("guardian", "Guardian"),
                ],
                default="member",
                max_length=16,
            ),
        ),
    ]
