# Generated by Django 5.2.14 on 2026-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_activity_guardian_accompanied_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
