# Generated by Django 5.2.14 on 2026-05-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_activity_is_hidden_post_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_announcement',
            field=models.BooleanField(default=False),
        ),
    ]
