# Generated by Django 5.2.14 on 2026-05-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_post_is_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='meeting_point',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='organizer_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='what_to_bring',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='membership',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='attendance_intent',
            field=models.CharField(choices=[('unknown', 'Not said'), ('going', 'Coming'), ('not_going', "Can't make it")], default='unknown', max_length=16),
        ),
    ]
