# Generated by Django 5.2.14 on 2026-05-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_activity_meeting_point_activity_organizer_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='met_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
