# Generated by Django 5.2.14 on 2026-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_membership_met_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='accessibility_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='beginners_welcome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='cost_band',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('free', 'Free'), ('low', 'Low cost'), ('paid', 'Paid')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='activity',
            name='difficulty',
            field=models.CharField(choices=[('unspecified', 'Not specified'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='unspecified', max_length=16),
        ),
    ]
