# Generated by Django 5.2.14 on 2026-05-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_activity_accessibility_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='welcomed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
