# Generated by Django 5.2.14 on 2026-05-30 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_membership_welcomed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social.post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['thread', 'reply_to', 'created_at'], name='social_post_thread__6db79a_idx'),
        ),
    ]
