# Generated by Django 5.2.14 on 2026-05-30 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_placeactivity_is_disputed_activityedgevote_and_more'),
        ('social', '0009_post_reply_to_post_social_post_thread__6db79a_idx'),
        ('taxonomy', '0005_seed_reading_archives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['cohort', 'activity_type'], name='social_acti_cohort_f4b41e_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['cohort', 'place'], name='social_acti_cohort_f1aa64_idx'),
        ),
    ]
