# Generated by Django 5.2.14 on 2026-06-02 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('social', '0011_postreaction'),
        ('taxonomy', '0005_seed_reading_archives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=16)),
                ('state', models.CharField(choices=[('member', 'Member'), ('left', 'Left'), ('removed', 'Removed')], default='member', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='thread',
            name='activity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='social.activity'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('type', 'Activity type'), ('category', 'Category')], max_length=8)),
                ('cohort', models.CharField(choices=[('unassigned', 'Unassigned'), ('child', 'Child (under 16)'), ('teen', 'Teen (16-17)'), ('adult', 'Adult (18+)')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_staff_curated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='taxonomy.activitytype')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='communities.area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='taxonomy.activitycategory')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='social.group'),
        ),
        migrations.AddConstraint(
            model_name='thread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', False), ('group__isnull', True)), models.Q(('activity__isnull', True), ('group__isnull', False)), _connector='OR'), name='thread_exactly_one_owner'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='social.group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['cohort', 'status'], name='social_grou_cohort_e2dbc1_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['cohort', 'area', 'activity_type'], name='social_grou_cohort_5b00ed_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['cohort', 'category'], name='social_grou_cohort_97a0db_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('activity_type__isnull', False), ('status', 'active')), fields=('cohort', 'area', 'activity_type'), name='uq_group_type'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('activity_type__isnull', True), ('status', 'active')), fields=('cohort', 'area', 'category'), name='uq_group_category'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity_type__isnull', False), ('tier', 'type')), models.Q(('activity_type__isnull', True), ('tier', 'category')), _connector='OR'), name='group_tier_matches_type'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'state'], name='social_grou_group_i_2dce7d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'state'], name='social_grou_user_id_fef22c_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'user'), name='uq_group_membership_group_user'),
        ),
    ]
