# Generated by Django 5.2.14 on 2026-06-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_groupmembership_alter_thread_activity_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='go_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='min_to_go',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
