# Generated by Django 5.2.14 on 2026-06-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_activity_go_confirmed_at_activity_min_to_go'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('co_organizer', 'Co-organizer'), ('member', 'Member'), ('guardian', 'Guardian')], default='member', max_length=16),
        ),
    ]
