# Generated by Django 5.2.14 on 2026-06-07 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_placeactivity_is_disputed_activityedgevote_and_more'),
        ('social', '0014_alter_membership_role'),
        ('taxonomy', '0005_seed_reading_archives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(choices=[('unassigned', 'Unassigned'), ('child', 'Child (under 16)'), ('teen', 'Teen (16-17)'), ('adult', 'Adult (18+)')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('meeting_point', models.TextField(blank=True, default='')),
                ('what_to_bring', models.TextField(blank=True, default='')),
                ('organizer_note', models.TextField(blank=True, default='')),
                ('accessibility_notes', models.TextField(blank=True, default='')),
                ('cost_band', models.CharField(choices=[('unspecified', 'Not specified'), ('free', 'Free'), ('low', 'Low cost'), ('paid', 'Paid')], default='unspecified', max_length=16)),
                ('difficulty', models.CharField(choices=[('unspecified', 'Not specified'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='unspecified', max_length=16)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('min_to_go', models.PositiveIntegerField(blank=True, null=True)),
                ('join_threshold', models.FloatField(default=0.6666666666666666)),
                ('guardian_accompanied', models.BooleanField(default=False)),
                ('beginners_welcome', models.BooleanField(default=False)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('monthly', 'Monthly')], max_length=16)),
                ('next_starts_at', models.DateTimeField()),
                ('anchor_day', models.PositiveSmallIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_series', to='taxonomy.activitytype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_series', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_series', to='places.place')),
            ],
            options={
                'verbose_name_plural': 'activity series',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='social.activityseries'),
        ),
        migrations.AddIndex(
            model_name='activityseries',
            index=models.Index(fields=['status', 'next_starts_at'], name='social_acti_status_519f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='activityseries',
            index=models.Index(fields=['owner'], name='social_acti_owner_i_aa7996_idx'),
        ),
        migrations.AddIndex(
            model_name='activityseries',
            index=models.Index(fields=['cohort', 'status'], name='social_acti_cohort_0585fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityseries',
            constraint=models.CheckConstraint(condition=models.Q(('join_threshold__gt', 0), ('join_threshold__lte', 1)), name='series_threshold_fraction'),
        ),
    ]
