# Generated by Django 5.2.14 on 2026-06-12 21:27

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_placeactivity_is_disputed_activityedgevote_and_more'),
        ('social', '0015_activityseries_activity_series_and_more'),
        ('taxonomy', '0005_seed_reading_archives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # gin_trgm_ops needs the pg_trgm extension (same pattern as the pgvector
        # extension in recommendations). Created here, before the first trigram index.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='activity_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='activity_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
