# Generated by Django 5.2.14 on 2026-06-12 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_title_trgm_event_event_desc_trgm'),
        ('places', '0005_placeactivity_is_disputed_activityedgevote_and_more'),
        ('social', '0016_activity_activity_title_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_posts', to='social.activity'),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_posts', to='events.event'),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_posts', to='places.place'),
        ),
    ]
