# Generated by Django 5.2.14 on 2026-06-12 23:01

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_placeactivity_is_disputed_activityedgevote_and_more'),
        ('social', '0017_post_shared_activity_post_shared_event_and_more'),
        ('taxonomy', '0005_seed_reading_archives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='activity_title_trgm',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='activity_desc_trgm',
        ),
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='activity_title_trgm'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'), name='activity_desc_trgm'),
        ),
    ]
