# Generated by Django 5.2.14 on 2026-06-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_remove_activity_activity_title_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='supervised',
            field=models.BooleanField(default=False),
        ),
    ]
