# Generated by Django 5.2.14 on 2026-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_activity_supervised'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityseries',
            name='supervised',
            field=models.BooleanField(default=False),
        ),
    ]
