# Generated by Django 5.2.15 on 2026-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_activityseries_supervised'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='getting_home_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activityseries',
            name='getting_home_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
