# Generated by Django 5.2.15 on 2026-06-14 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_placecorrection_placecorrectionconfirmation_and_more'),
        ('social', '0021_activity_getting_home_note_and_more'),
        ('taxonomy', '0005_seed_reading_archives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(choices=[('unassigned', 'Unassigned'), ('child', 'Child (under 16)'), ('teen', 'Teen (16-17)'), ('adult', 'Adult (18+)')], max_length=16)),
                ('coarse_window', models.CharField(choices=[('weekday_daytime', 'Weekday daytime'), ('weekday_evening', 'Weekday evening'), ('weekend_daytime', 'Weekend daytime'), ('weekend_evening', 'Weekend evening')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='taxonomy.activitytype')),
                ('converted_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_interest', to='social.activity')),
                ('interested_users', models.ManyToManyField(blank=True, related_name='gauge_interests', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interests', to='places.place')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['cohort', 'expires_at'], name='social_acti_cohort_50227f_idx')],
            },
        ),
    ]
