# Generated by Django 5.2.15 on 2026-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_activityinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='first_time_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
