# Generated by Django 5.2.14 on 2026-06-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_activity_first_time_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='transit_status',
            field=models.CharField(choices=[('none', 'Not said'), ('on_my_way', 'On my way'), ('running_late', 'Running late')], default='none', max_length=16),
        ),
    ]
