# Generated by Django 5.2.14 on 2026-06-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_membership_transit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fallback_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
