# Generated by Django 5.2.14 on 2026-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_activity_fallback_starts_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityseries',
            name='next_instance_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
