# Generated by Django 5.2.14 on 2026-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0026_activityseries_next_instance_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="fallback_meeting_point",
            field=models.TextField(blank=True, default=""),
        ),
    ]
