# Generated by Django 5.2.14 on 2026-06-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0027_activity_fallback_meeting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='departing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
