# Generated by Django 5.2.14 on 2026-06-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_membership_departing_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='brings_support_person',
            field=models.BooleanField(default=False),
        ),
    ]
