# Generated by Django 5.2.14 on 2026-06-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_membership_brings_support_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_publicly_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_publicly_listed',
            field=models.BooleanField(default=True),
        ),
    ]
