# Generated by Django 5.2.15 on 2026-06-21 12:35
#
# Privacy by default (invariant #4): anonymous public discovery is now opt-IN. Migration 0030 added
# is_publicly_listed with default=True, which back-filled EVERY existing activity/group to publicly
# listed without the organiser ever choosing it. This migration flips the default to False AND resets
# all existing rows to False, so nothing is anonymously discoverable until an ADULT organiser
# explicitly opts in via set_public_listing. (The feature shipped only ~1 day earlier, so this
# un-lists at most a brand-new, near-empty set; organisers re-opt-in deliberately.)

from django.db import migrations, models


def unlist_all(apps, schema_editor):
    Activity = apps.get_model("social", "Activity")
    Group = apps.get_model("social", "Group")
    Activity.objects.filter(is_publicly_listed=True).update(is_publicly_listed=False)
    Group.objects.filter(is_publicly_listed=True).update(is_publicly_listed=False)


def noop(apps, schema_editor):
    # Deliberately irreversible-as-noop: re-listing everyone on rollback would re-introduce the
    # privacy regression this migration fixes.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0030_activity_group_public_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="is_publicly_listed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="group",
            name="is_publicly_listed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(unlist_all, noop),
    ]
