# Generated by Django 5.2.15 on 2026-07-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0032_activity_cost_amount_cost_note'),
        ('taxonomy', '0006_seed_ro_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='secondary_types',
            field=models.ManyToManyField(blank=True, related_name='secondary_activities', to='taxonomy.activitytype'),
        ),
    ]
