# Generated by Django 5.2.15 on 2026-07-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_activity_secondary_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityseries',
            name='cost_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='activityseries',
            name='cost_note',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
