# Generated by Django 5.2.15 on 2026-07-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_activityseries_cost_amount_activityseries_cost_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='fallback_meeting_point',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='fallback_starts_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='getting_home_note',
        ),
        migrations.RemoveField(
            model_name='activityseries',
            name='getting_home_note',
        ),
    ]
