# Generated by Django 5.2.16 on 2026-07-14 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0037_migrate_reaction_emojis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postdissent',
            index=models.Index(fields=['created_at'], name='social_post_created_cd6036_idx'),
        ),
    ]
