# Generated by Django 5.1.15 on 2026-05-27 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="taxonomy.activitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activity categories",
            },
        ),
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_types",
                        to="taxonomy.activitycategory",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="taxonomy.activitytype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("related", "Related to"),
                            ("synonym", "Synonym of"),
                            ("variant", "Variant of"),
                            ("requires", "Requires"),
                        ],
                        default="related",
                        max_length=16,
                    ),
                ),
                ("symmetric", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_out",
                        to="taxonomy.activitytype",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations_in",
                        to="taxonomy.activitytype",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="activitycategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="category_not_self_parent",
            ),
        ),
        migrations.AddIndex(
            model_name="activitytype",
            index=models.Index(
                fields=["category"], name="taxonomy_ac_categor_907ff1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="activitytype",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="type_not_self_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrelation",
            constraint=models.UniqueConstraint(
                fields=("source", "target", "kind"), name="uq_activity_relation"
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="relation_not_self",
            ),
        ),
    ]
