# Generated by Django 5.2.14 on 2026-05-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_seed_taxonomy"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytype",
            name="family_friendly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activitytype",
            name="wellness",
            field=models.BooleanField(default=False),
        ),
    ]
