# Generated by Django 5.2.14 on 2026-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('join_requested', 'Join requested'), ('join_approved', 'Join approved'), ('event_reminder', 'Event reminder'), ('activity_cancelled', 'Activity cancelled'), ('activity_updated', 'Activity updated'), ('announcement', 'Organizer announcement'), ('arrival', 'Arrival'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('moderation', 'Moderation notice'), ('system', 'System')], default='system', max_length=24),
        ),
    ]
