# Generated by Django 5.2.14 on 2026-06-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('join_requested', 'Join requested'), ('join_approved', 'Join approved'), ('event_reminder', 'Event reminder'), ('activity_cancelled', 'Activity cancelled'), ('activity_updated', 'Activity updated'), ('announcement', 'Organizer announcement'), ('group_announcement', 'Group announcement'), ('meetup_confirmed', 'Meetup confirmed'), ('arrival', 'Arrival'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('mention', 'Mention'), ('organizer_role', 'Organizer role changed'), ('moderation', 'Moderation notice'), ('system', 'System')], default='system', max_length=24),
        ),
    ]
