# Generated by Django 5.2.16 on 2026-07-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_notif_recipient_created_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('join_requested', 'Join requested'), ('join_approved', 'Join approved'), ('event_reminder', 'Event reminder'), ('activity_cancelled', 'Activity cancelled'), ('activity_updated', 'Activity updated'), ('announcement', 'Organizer announcement'), ('group_announcement', 'Group announcement'), ('meetup_confirmed', 'Meetup confirmed'), ('arrival', 'Arrival'), ('connection_request', 'Connection request'), ('connection_accepted', 'Connection accepted'), ('mention', 'Mention'), ('organizer_role', 'Organizer role changed'), ('activity_match', 'Saved-search match'), ('gauge_match', 'Saved-search gauge match'), ('group_question', 'Group question'), ('interest_converted', 'Gauge converted'), ('rsvp_nudge', 'RSVP nudge'), ('organizer_prep', 'Organizer prep reminder'), ('supervisor_needed', 'Supervisor needed'), ('formative_note', 'Formative note'), ('mod_alert', 'Moderator alert'), ('moderation', 'Moderation notice'), ('system', 'System')], default='system', max_length=24),
        ),
    ]
