package authcore

import (
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"golang.org/x/crypto/argon2"
	"golang.org/x/crypto/bcrypt"
	"testing"
)

func TestDjangoDefaultLegacyHashers(t *testing.T) {
	password := "correct horse battery"
	hashes := []string{
		"pbkdf2_sha1$1000$legacy-salt$tSA8+k747cFZReUB/dfApNJJDkI=",
		"scrypt$16384$legacy-salt$8$5$DrkIOaOPvXoBES+cnbkxqp2J7f6bxqNjfsXiRPxLCCykGwsuTj1IZLC1RlCAGeb358a8/krDQK/u7upLgNgbcQ==",
	}
	// bcrypt and Argon2 encodings match Django's exact format; PBKDF2/Scrypt
	// expected bytes above are independently generated by Python hashlib.
	digest := sha256.Sum256([]byte(password))
	bcryptHash, err := bcrypt.GenerateFromPassword([]byte(hex.EncodeToString(digest[:])), 4)
	if err != nil {
		t.Fatal(err)
	}
	hashes = append(hashes, "bcrypt_sha256$"+string(bcryptHash))
	plainBcrypt, err := bcrypt.GenerateFromPassword([]byte(password), 4)
	if err != nil {
		t.Fatal(err)
	}
	hashes = append(hashes, "bcrypt$"+string(plainBcrypt))
	salt := []byte("independent-salt")
	key := argon2.IDKey([]byte(password), salt, 2, 102400, 8, 32)
	hashes = append(hashes, fmt.Sprintf("argon2$argon2id$v=19$m=102400,t=2,p=8$%s$%s", base64.RawStdEncoding.EncodeToString(salt), base64.RawStdEncoding.EncodeToString(key)))
	for _, encoded := range hashes {
		ok, err := VerifyPassword(context.Background(), password, encoded)
		if err != nil || !ok {
			t.Fatalf("legacy %s rejected: %v", encoded[:10], err)
		}
		ok, err = VerifyPassword(context.Background(), "incorrect password", encoded)
		if err != nil || ok {
			t.Fatal("legacy accepted wrong password")
		}
	}
	for _, encoded := range []string{"scrypt$1048576$salt$32$16$invalid", "argon2$argon2id$v=19$m=999999999,t=99,p=200$salt$invalid", "bcrypt_sha256$$2b$31$bad"} {
		ok, err := VerifyPassword(context.Background(), password, encoded)
		if err != nil || ok {
			t.Fatal("unbounded legacy hash work accepted")
		}
	}
}
