# Generated by Django 5.2.14 on 2026-05-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_backfill_chatmessage_to_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
